function queryElement<T extends Element>(root: Document, selector: string): T {
  const element = root.querySelector<T>(selector);
  if (!element) {
    throw new Error(`Missing required element: ${selector}`);
  }

  return element;
}

export function queryMikroSlidesElement<T extends Element>(
  selector: string,
  root: Document = document,
): T {
  return queryElement<T>(root, selector);
}

export function createMikroSlidesElements(root: Document = document) {
  return {
    html: root.documentElement,
    appShell: queryElement<HTMLElement>(root, "#app-shell"),
    deckTitleInput: queryElement<HTMLInputElement>(root, "#deck-title-input"),
    deckMeta: queryElement<HTMLElement>(root, "#deck-meta"),
    slideList: queryElement<HTMLElement>(root, "#slide-list"),
    slideCanvas: queryElement<HTMLElement>(root, "#slide-canvas"),
    speakerNotes: queryElement<HTMLTextAreaElement>(root, "#speaker-notes"),
    toast: queryElement<HTMLElement>(root, "#toast"),
    printDeck: queryElement<HTMLElement>(root, "#print-deck"),
    newDeckButton: queryElement<HTMLButtonElement>(root, "#new-deck-btn"),
    libraryButton: queryElement<HTMLButtonElement>(root, "#library-btn"),
    importJsonButton: queryElement<HTMLButtonElement>(root, "#import-json-btn"),
    outlineButton: queryElement<HTMLButtonElement>(root, "#outline-btn"),
    polishButton: queryElement<HTMLButtonElement>(root, "#polish-btn"),
    exportButton: queryElement<HTMLButtonElement>(root, "#export-btn"),
    presentButton: queryElement<HTMLButtonElement>(root, "#present-btn"),
    commandButton: queryElement<HTMLButtonElement>(root, "#command-btn"),
    themeButton: queryElement<HTMLButtonElement>(root, "#theme-btn"),
    themeIcon: queryElement<SVGUseElement>(root, "#theme-icon"),
    addSlideButton: queryElement<HTMLButtonElement>(root, "#add-slide-btn"),
    undoButton: queryElement<HTMLButtonElement>(root, "#undo-btn"),
    redoButton: queryElement<HTMLButtonElement>(root, "#redo-btn"),
    addTextButton: queryElement<HTMLButtonElement>(root, "#add-text-btn"),
    addShapeButton: queryElement<HTMLButtonElement>(root, "#add-shape-btn"),
    addImageButton: queryElement<HTMLButtonElement>(root, "#add-image-btn"),
    templateSelect: queryElement<HTMLSelectElement>(root, "#template-select"),
    saveTemplateButton: queryElement<HTMLButtonElement>(root, "#save-template-btn"),
    duplicateElementButton: queryElement<HTMLButtonElement>(root, "#duplicate-element-btn"),
    duplicateSlideButton: queryElement<HTMLButtonElement>(root, "#duplicate-slide-btn"),
    deleteSlideButton: queryElement<HTMLButtonElement>(root, "#delete-slide-btn"),
    zoomOutButton: queryElement<HTMLButtonElement>(root, "#zoom-out-btn"),
    zoomFitButton: queryElement<HTMLButtonElement>(root, "#zoom-fit-btn"),
    zoomInButton: queryElement<HTMLButtonElement>(root, "#zoom-in-btn"),
    libraryDialog: queryElement<HTMLDialogElement>(root, "#library-dialog"),
    librarySearch: queryElement<HTMLInputElement>(root, "#library-search"),
    deckList: queryElement<HTMLElement>(root, "#deck-list"),
    imageDialog: queryElement<HTMLDialogElement>(root, "#image-dialog"),
    imageUrlInput: queryElement<HTMLInputElement>(root, "#image-url-input"),
    imageFileInput: queryElement<HTMLInputElement>(root, "#image-file-input"),
    insertImageButton: queryElement<HTMLButtonElement>(root, "#insert-image-btn"),
    jsonFileInput: queryElement<HTMLInputElement>(root, "#json-file-input"),
    slideInspector: queryElement<HTMLElement>(root, "#slide-inspector"),
    slideTitleInput: queryElement<HTMLInputElement>(root, "#slide-title-input"),
    deckThemeSelect: queryElement<HTMLSelectElement>(root, "#deck-theme-select"),
    deckAspectSelect: queryElement<HTMLSelectElement>(root, "#deck-aspect-select"),
    slideBackgroundInput: queryElement<HTMLInputElement>(root, "#slide-background-input"),
    backgroundSwatches: queryElement<HTMLElement>(root, "#background-swatches"),
    elementInspector: queryElement<HTMLElement>(root, "#element-inspector"),
    objectInspectorTitle: queryElement<HTMLElement>(root, "#object-inspector-title"),
    deleteElementButton: queryElement<HTMLButtonElement>(root, "#delete-element-btn"),
    elementXInput: queryElement<HTMLInputElement>(root, "#element-x-input"),
    elementYInput: queryElement<HTMLInputElement>(root, "#element-y-input"),
    elementWidthInput: queryElement<HTMLInputElement>(root, "#element-width-input"),
    elementHeightInput: queryElement<HTMLInputElement>(root, "#element-height-input"),
    elementOpacityInput: queryElement<HTMLInputElement>(root, "#element-opacity-input"),
    textFields: queryElement<HTMLElement>(root, "#text-fields"),
    textContentInput: queryElement<HTMLTextAreaElement>(root, "#text-content-input"),
    textFontSelect: queryElement<HTMLSelectElement>(root, "#text-font-select"),
    manageFontsButton: queryElement<HTMLButtonElement>(root, "#manage-fonts-btn"),
    textSizeInput: queryElement<HTMLInputElement>(root, "#text-size-input"),
    textWeightInput: queryElement<HTMLInputElement>(root, "#text-weight-input"),
    textColorInput: queryElement<HTMLInputElement>(root, "#text-color-input"),
    shapeFields: queryElement<HTMLElement>(root, "#shape-fields"),
    shapeKindSelect: queryElement<HTMLSelectElement>(root, "#shape-kind-select"),
    shapeFillInput: queryElement<HTMLInputElement>(root, "#shape-fill-input"),
    shapeStrokeInput: queryElement<HTMLInputElement>(root, "#shape-stroke-input"),
    imageFields: queryElement<HTMLElement>(root, "#image-fields"),
    imageSrcInput: queryElement<HTMLInputElement>(root, "#image-src-input"),
    imageAltInput: queryElement<HTMLInputElement>(root, "#image-alt-input"),
    imageFitSelect: queryElement<HTMLSelectElement>(root, "#image-fit-select"),
    layersSection: queryElement<HTMLElement>(root, "#layers-section"),
    layersList: queryElement<HTMLElement>(root, "#layers-list"),
    layerFrontButton: queryElement<HTMLButtonElement>(root, "#layer-front-btn"),
    layerForwardButton: queryElement<HTMLButtonElement>(root, "#layer-forward-btn"),
    layerBackwardButton: queryElement<HTMLButtonElement>(root, "#layer-backward-btn"),
    layerBackButton: queryElement<HTMLButtonElement>(root, "#layer-back-btn"),
    templateDialog: queryElement<HTMLDialogElement>(root, "#template-dialog"),
    templateNameInput: queryElement<HTMLInputElement>(root, "#template-name-input"),
    saveTemplateConfirmButton: queryElement<HTMLButtonElement>(root, "#save-template-confirm-btn"),
    fontDialog: queryElement<HTMLDialogElement>(root, "#font-dialog"),
    fontList: queryElement<HTMLElement>(root, "#font-list"),
    fontNameInput: queryElement<HTMLInputElement>(root, "#font-name-input"),
    fontFileInput: queryElement<HTMLInputElement>(root, "#font-file-input"),
    addLocalFontButton: queryElement<HTMLButtonElement>(root, "#add-local-font-btn"),
    fontSourceCatalog: queryElement<HTMLElement>(root, "#font-source-catalog"),
    fontSearchInput: queryElement<HTMLInputElement>(root, "#font-search-input"),
    fontCategoryList: queryElement<HTMLElement>(root, "#font-category-list"),
    fontCatalog: queryElement<HTMLElement>(root, "#font-catalog"),
    fontCatalogStatus: queryElement<HTMLElement>(root, "#font-catalog-status"),
    loadFontCatalogButton: queryElement<HTMLButtonElement>(root, "#load-font-catalog-btn"),
    exportDialog: queryElement<HTMLDialogElement>(root, "#export-dialog"),
    exportStatus: queryElement<HTMLElement>(root, "#export-status"),
    exportJsonAction: queryElement<HTMLButtonElement>(root, "#export-json-action"),
    exportPortableAction: queryElement<HTMLButtonElement>(root, "#export-portable-action"),
    exportPdfAction: queryElement<HTMLButtonElement>(root, "#export-pdf-action"),
    exportPngAction: queryElement<HTMLButtonElement>(root, "#export-png-action"),
    outlineDialog: queryElement<HTMLDialogElement>(root, "#outline-dialog"),
    outlineInput: queryElement<HTMLTextAreaElement>(root, "#outline-input"),
    createOutlineDeckButton: queryElement<HTMLButtonElement>(root, "#create-outline-deck-btn"),
    commandDialog: queryElement<HTMLDialogElement>(root, "#command-dialog"),
    commandInput: queryElement<HTMLInputElement>(root, "#command-input"),
    commandList: queryElement<HTMLElement>(root, "#command-list"),
    contextMenu: queryElement<HTMLElement>(root, "#context-menu"),
    presenterDialog: queryElement<HTMLDialogElement>(root, "#presenter-dialog"),
    presenterSlide: queryElement<HTMLElement>(root, "#presenter-slide"),
    presenterMeta: queryElement<HTMLElement>(root, "#presenter-meta"),
    presenterPrevButton: queryElement<HTMLButtonElement>(root, "#presenter-prev-btn"),
    presenterNextButton: queryElement<HTMLButtonElement>(root, "#presenter-next-btn"),
  };
}

export type MikroSlidesElements = ReturnType<typeof createMikroSlidesElements>;
